# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mark/github/UFI1/front/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.root = QtWidgets.QWidget(MainWindow)
        self.root.setMinimumSize(QtCore.QSize(0, 0))
        self.root.setAutoFillBackground(False)
        self.root.setObjectName("root")
        self.formLayoutWidget = QtWidgets.QWidget(self.root)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.comLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.comLayout.setContentsMargins(0, 0, 0, 0)
        self.comLayout.setObjectName("comLayout")
        self.comIdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.comIdLabel.setObjectName("comIdLabel")
        self.comLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comIdLabel)
        self.comIdComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comIdComboBox.setObjectName("comIdComboBox")
        self.comLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comIdComboBox)
        self.brLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.brLabel.setObjectName("brLabel")
        self.comLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.brLabel)
        self.brComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.brComboBox.setObjectName("brComboBox")
        self.comLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.brComboBox)
        self.dbLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dbLabel.setObjectName("dbLabel")
        self.comLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dbLabel)
        self.dbComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.dbComboBox.setObjectName("dbComboBox")
        self.comLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dbComboBox)
        self.sbLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sbLabel.setObjectName("sbLabel")
        self.comLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sbLabel)
        self.sbComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.sbComboBox.setObjectName("sbComboBox")
        self.comLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbComboBox)
        self.pbLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.pbLabel.setObjectName("pbLabel")
        self.comLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pbLabel)
        self.pbComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.pbComboBox.setObjectName("pbComboBox")
        self.comLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pbComboBox)
        self.actionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.actionLabel.setObjectName("actionLabel")
        self.comLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.actionLabel)
        self.actionCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.actionCheckBox.setText("")
        self.actionCheckBox.setObjectName("actionCheckBox")
        self.comLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.actionCheckBox)
        self.clearBtLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.clearBtLabel.setObjectName("clearBtLabel")
        self.comLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.clearBtLabel)
        self.clearButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.comLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.clearButton)
        self.uartText = QtWidgets.QTextEdit(self.root)
        self.uartText.setGeometry(QtCore.QRect(180, 10, 611, 221))
        self.uartText.setObjectName("uartText")
        MainWindow.setCentralWidget(self.root)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comIdLabel.setText(_translate("MainWindow", "comId"))
        self.brLabel.setText(_translate("MainWindow", "br"))
        self.dbLabel.setText(_translate("MainWindow", "db"))
        self.sbLabel.setText(_translate("MainWindow", "sb"))
        self.pbLabel.setText(_translate("MainWindow", "pb"))
        self.actionLabel.setText(_translate("MainWindow", "action"))
        self.clearBtLabel.setText(_translate("MainWindow", "clearBt"))
        self.clearButton.setText(_translate("MainWindow", "PushButton"))
